import { useState, useEffect } from 'react'
import { Clock, X } from 'lucide-react'
import type { CourierAgent, Department } from '../lib/fmsService'

interface CreateRecordModalProps {
  workflowType: 'outward' | 'inward'
  isOpen: boolean
  onClose: () => void
  onSubmit: (formData: RecordFormValues) => Promise<void>
  courierAgents: CourierAgent[]
  departments: Department[]
}

export interface RecordFormValues {
  [key: string]: any
}

export function CreateRecordModal({
  workflowType,
  isOpen,
  onClose,
  onSubmit,
  courierAgents,
  departments,
}: CreateRecordModalProps) {
  const [loading, setLoading] = useState(false)
  const [nowStr, setNowStr] = useState('')
  const [formData, setFormData] = useState<RecordFormValues>({})

  useEffect(() => {
    if (isOpen) {
      setNowStr(new Date().toLocaleString())
      setFormData({})
    }
  }, [isOpen])

  if (!isOpen) return null

  const isOutward = workflowType === 'outward'

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setLoading(true)
    try {
      await onSubmit(formData)
      onClose()
    } finally {
      setLoading(false)
    }
  }

  function handleFieldChange(field: string, value: any) {
    setFormData(prev => ({ ...prev, [field]: value }))
  }

  return (
    <div className="modal-backdrop">
      <div className="modal-card" style={{ maxWidth: '750px' }}>
        <div className="modal-header">
          <div>
            <h2>{isOutward ? 'New Outward Courier Request' : 'New Inward Docket Receipt'}</h2>
            <p>
              {isOutward
                ? 'Initiates Stage 1: Request with sender and dispatch requirements'
                : 'Initiates Stage 1: Docket Received with reception intake log'}
            </p>
          </div>
          <button className="modal-close-btn" onClick={onClose} disabled={loading}>
            <X size={20} />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="modal-form">
          <div style={{ background: '#f8fafc', padding: '12px', borderRadius: '8px', border: '1px solid #e2e8f0', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Clock size={16} color="#64748b" />
            <div>
              <div style={{ fontSize: '0.85rem', fontWeight: 600, color: '#334155' }}>Timestamp</div>
              <div style={{ fontSize: '0.95rem', color: '#0f172a' }}>{nowStr}</div>
              <div style={{ fontSize: '0.75rem', color: '#64748b' }}>Automatically generated by server upon submission</div>
            </div>
          </div>

          {isOutward ? (
            <>
              <div className="form-row">
                <div className="form-group">
                  <label>Courier Agent *</label>
                  <select required value={formData.courier_agent_id || ''} onChange={e => handleFieldChange('courier_agent_id', e.target.value)}>
                    <option value="" disabled>Select Courier...</option>
                    {courierAgents.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}
                  </select>
                </div>
                <div className="form-group">
                  <label>Requested By *</label>
                  <input type="text" required placeholder="Employee Name / ID" value={formData.requested_by || ''} onChange={e => handleFieldChange('requested_by', e.target.value)} />
                </div>
              </div>
              <div className="form-group">
                <label>Sample Detail *</label>
                <input type="text" required placeholder="Describe the sample or item" value={formData.sample_detail || ''} onChange={e => handleFieldChange('sample_detail', e.target.value)} />
              </div>
              <div className="form-row">
                <div className="form-group">
                  <label>Company Name *</label>
                  <input type="text" required placeholder="Company Name" value={formData.company_name || ''} onChange={e => handleFieldChange('company_name', e.target.value)} />
                </div>
                <div className="form-group">
                  <label>Contact Person *</label>
                  <input type="text" required placeholder="Person Name" value={formData.contact_person || ''} onChange={e => handleFieldChange('contact_person', e.target.value)} />
                </div>
              </div>
              <div className="form-row">
                <div className="form-group">
                  <label>City *</label>
                  <input type="text" required placeholder="City" value={formData.city || ''} onChange={e => handleFieldChange('city', e.target.value)} />
                </div>
                <div className="form-group">
                  <label>Contact Number</label>
                  <input type="text" placeholder="+91..." value={formData.contact_number || ''} onChange={e => handleFieldChange('contact_number', e.target.value)} />
                </div>
              </div>
              <div className="form-group">
                <label>Address</label>
                <textarea rows={2} placeholder="Full Address" value={formData.address || ''} onChange={e => handleFieldChange('address', e.target.value)} />
              </div>
              
              <div className="form-row">
                <div className="form-group">
                  <label>Courier Type *</label>
                  <select required value={formData.courier_type || ''} onChange={e => handleFieldChange('courier_type', e.target.value)}>
                    <option value="" disabled>Select Type...</option>
                    <option value="Document">Document</option>
                    <option value="Parcel">Parcel</option>
                    <option value="Sample">Sample</option>
                  </select>
                </div>
                <div className="form-group" style={{ display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '24px' }}>
                  <label style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <input type="checkbox" checked={formData.customer_send || false} onChange={e => handleFieldChange('customer_send', e.target.checked)} />
                    Customer Send
                  </label>
                </div>
              </div>

              <div className="form-row" style={{ marginTop: '8px' }}>
                <label style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <input type="checkbox" checked={formData.plastic || false} onChange={e => handleFieldChange('plastic', e.target.checked)} /> Plastic
                </label>
                <label style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <input type="checkbox" checked={formData.foil || false} onChange={e => handleFieldChange('foil', e.target.checked)} /> Foil
                </label>
                <label style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <input type="checkbox" checked={formData.aluminium || false} onChange={e => handleFieldChange('aluminium', e.target.checked)} /> Aluminium
                </label>
                <label style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <input type="checkbox" checked={formData.accounts || false} onChange={e => handleFieldChange('accounts', e.target.checked)} /> Accounts
                </label>
              </div>
            </>
          ) : (
            <>
              {/* Inward Fields */}
              <div className="form-row">
                <div className="form-group">
                  <label>Docket Number *</label>
                  <input type="text" required placeholder="e.g. BD-12345" value={formData.docket_number || ''} onChange={e => handleFieldChange('docket_number', e.target.value)} />
                </div>
                <div className="form-group">
                  <label>Dispatch Date</label>
                  <input type="date" value={formData.dispatch_date || ''} onChange={e => handleFieldChange('dispatch_date', e.target.value)} />
                </div>
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label>Courier Agent *</label>
                  <select required value={formData.courier_agent_id || ''} onChange={e => handleFieldChange('courier_agent_id', e.target.value)}>
                    <option value="" disabled>Select Courier...</option>
                    {courierAgents.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}
                  </select>
                </div>
                <div className="form-group">
                  <label>Agent Number</label>
                  <input type="text" placeholder="Agent Contact/Ref" value={formData.agent_number || ''} onChange={e => handleFieldChange('agent_number', e.target.value)} />
                </div>
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label>Supplier *</label>
                  <input type="text" required placeholder="Supplier Name" value={formData.supplier_id || ''} onChange={e => handleFieldChange('supplier_id', e.target.value)} />
                </div>
                <div className="form-group">
                  <label>From Location *</label>
                  <input type="text" required placeholder="City/Origin" value={formData.from_location || ''} onChange={e => handleFieldChange('from_location', e.target.value)} />
                </div>
              </div>

              <div className="form-group">
                <label>Material *</label>
                <input type="text" required placeholder="Description of material" value={formData.material || ''} onChange={e => handleFieldChange('material', e.target.value)} />
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label>Department *</label>
                  <select required value={formData.department_id || ''} onChange={e => handleFieldChange('department_id', e.target.value)}>
                    <option value="" disabled>Select Department...</option>
                    {departments.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}
                  </select>
                </div>
                <div className="form-group">
                  <label>Delivery Type *</label>
                  <select required value={formData.delivery_type || ''} onChange={e => handleFieldChange('delivery_type', e.target.value)}>
                    <option value="" disabled>Select Type...</option>
                    <option value="Standard">Standard</option>
                    <option value="Express">Express</option>
                    <option value="Hand Delivery">Hand Delivery</option>
                  </select>
                </div>
              </div>
            </>
          )}

          <div className="modal-actions" style={{ marginTop: '24px' }}>
            <button type="button" className="btn-secondary" onClick={onClose} disabled={loading}>
              Cancel
            </button>
            <button type="submit" className="btn-primary" disabled={loading}>
              {loading ? 'Saving...' : 'Submit Stage 1'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
